spring:
  h2:
    console:
      enabled: TRUE
  jpa:
    hibernate:
      ddl-auto: create # 서버 시작에 테이블 생성
spring.datasource.url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
          